### ISSUE TITLE
Fjerne rar tekst?

### ISSUE THREAD

**Issue by HavardLine** [elateas/phb#20]
Hei!

Jeg lette etter rutiner og prosedyrer i dag. Fant tilfeldigvis denne plassen med søket "personalhåndbok" på github.

Flott at dette plassen finnes, og egentlig litt rart at det ikke er flere som samarbeider for å klare den norske internkontrollforskriften.

Til påenget: Det hadde vert enklere for meg, som tilfeldigvis er innom, om dere skrev "TODO: fullføre avsnitt" i stedet for å fylle med tekst på et rart språk.

MVH
Håvard

**Comment by tolu** [comment]
Bra poäng 😄 
Det skulle göra saker å ting enklare även för oss tror jag.

Tack för kommentaren!
